.RECIPEPREFIX = >

a.out: source.c
> gcc -L/home/pozhang/projects/operating_systems/lib -Wl,-rpath=/home/pozhang/projects/operating_systems/lib -Wall -pthread source.c -lutil

clean: 
> rm -f *.o *.out
